INSERT INTO users (name, email, password) VALUES
('Administrador', 'admin@mrdrives.com.br', '$2y$12$03cQS0ifwFZIXXwqDAYwQOpRGRFwzCvz9ny/ANIhNIGrE9xPw2uaK');

INSERT INTO products
(name, model_code, category, short_description, full_description, power, voltage, recommended_applications, technical_specs, main_image, manual_pdf, is_active, is_featured, sort_order)
VALUES
('Inversor MRD-320 220V', 'MRD-320 220V', 'Inversores de frequência', 'Inversor vetorial compacto para redes 220V com excelente custo-benefício.', 'Modelo MRD-320 indicado para redes 220V, com controle vetorial, painel intuitivo e alta estabilidade para aplicações industriais.', '0.4 kW a 5.5 kW', '220 V', 'Esteiras, ventiladores, máquinas industriais, bombas e sistemas de embalagem', 'Controle vetorial\nDisplay duplo LED\nPotenciômetro integrado\nEntradas digitais e analógicas\nSuporte para frenagem conforme aplicação', 'assets/img/mrd600/mrd600_2.jpeg', NULL, 1, 1, 10),
('Inversor MRD-320 380V', 'MRD-320 380V', 'Inversores de frequência', 'Modelo trifásico para aplicações industriais com potência até 7.5 kW.', 'Modelo MRD-320 para rede 380V, recomendado para máquinas industriais, ventiladores, bombas e linhas produtivas que exigem estabilidade e ajuste rápido.', '0.4 kW a 7.5 kW', '380 V', 'Bombas de recalque, ventiladores, máquinas têxteis e máquinas de marcenaria', 'Entrada trifásica\nControle vetorial\nRS485 opcional\nFrenagem dinâmica conforme configuração\nGarantia estendida', 'assets/img/mrd600/mrd600_2.jpeg', NULL, 1, 1, 20),
('MRD-320 Interface e Controle', 'MRD-320 I/O', 'Soluções industriais', 'Configuração com display duplo LED, potenciômetro integrado e conexões de controle.', 'Solução para projetos que precisam de operação rápida, leitura clara de parâmetros, comandos diretos e integração por sinais digitais, analógicos e comunicação.', 'Conforme projeto', '220 V / 380 V', 'Painéis industriais, OEM, ODM e integração com máquinas', 'Display duplo LED\nRUN e STOP/RES\nEntradas X1 a X5\nAI, AO, 10V, GND e RS485\nBornes para frenagem P+ e PB', 'assets/img/mrd600/mrd600_2.jpeg', NULL, 1, 0, 30),
('Inversor MRD700/IP65', 'MRD700/IP65', 'Inversores de frequência IP65', 'Inversor lavável IP65 para ambientes severos, com STO, comunicação industrial e interfaces completas.', 'O MRD700/IP65 combina gabinete protegido, painel LED com dupla exibição, LCD multilíngue, arquitetura modular e ampla compatibilidade de comunicação para bombas fotovoltaicas, motores síncronos e assíncronos, elevadores, guindastes e máquinas industriais.', '0.4 kW a 400 kW', '220 V / 380 V / 480 V', 'Bombas fotovoltaicas, motores síncronos, motores assíncronos, elevadores, guindastes, esteiras, ventiladores e ambientes com poeira ou umidade', 'Proteção IP65\nFunção STO integrada\n7 terminais multifuncionais\n2 entradas AI\n2 saídas de relé e saída AO\nPT100/PT1000\nPID e PLC integrados\nSVC, V/F, FVC e controle de torque\nRS485, PROFIBUS, PROFINET, CANopen, EtherCAT, Modbus TCP e PG', 'assets/img/mrd700-ip65/mrd700ip65.png', NULL, 1, 1, 40);

