<?php $isPrivacy = ($slug ?? '') === 'politica-de-privacidade'; ?>
<?php $usesModernPolicyLayout = in_array(($slug ?? ''), ['politica-de-privacidade', 'politica-de-entrega', 'trocas-e-devolucoes', 'garantia'], true); ?>
<?php $modernKicker = match ($slug ?? '') { 'politica-de-privacidade' => 'Privacidade e proteção de dados', 'politica-de-entrega' => 'Entrega, frete e recebimento', 'trocas-e-devolucoes' => 'Trocas e atendimento ao consumidor', 'garantia' => 'Garantia e suporte técnico', default => 'Informações legais e comerciais' }; ?>
<?php if (!$usesModernPolicyLayout): ?><nav class="shop-breadcrumb" aria-label="Navegação estrutural"><a href="/">Início</a><span>/</span><strong><?= e($page['title']) ?></strong></nav><?php endif; ?>
<article class="legal-page<?= $usesModernPolicyLayout ? ' legal-page--privacy' : '' ?>">
    <header><span class="shop-kicker"><?= e($modernKicker) ?></span><h1><?= e($page['title']) ?></h1><p><?= e($page['intro']) ?></p><small>Última atualização: <?= date('d/m/Y') ?></small></header>
    <div class="legal-layout">
        <aside><strong><?= $usesModernPolicyLayout ? 'Conteúdo da política' : 'Nesta página' ?></strong><?php foreach ($page['sections'] as $index => $section): ?><a href="#secao-<?= $index + 1 ?>"<?= $usesModernPolicyLayout && $index === 0 ? ' class="is-active" aria-current="true"' : '' ?>><span><?= str_pad((string) ($index + 1), 2, '0', STR_PAD_LEFT) ?></span><?= e($section[0]) ?></a><?php endforeach; ?><?php if (!$usesModernPolicyLayout): ?><a href="#contato-legal"><span>→</span>Fale conosco</a><?php endif; ?></aside>
        <div class="legal-content">
            <?php foreach ($page['sections'] as $index => $section): ?><section id="secao-<?= $index + 1 ?>"><span><?= str_pad((string) ($index + 1), 2, '0', STR_PAD_LEFT) ?></span><div><h2><?= e($section[0]) ?></h2><p><?= e($section[1]) ?></p><?php if (!empty($section[2]) && is_array($section[2])): ?><ul><?php foreach ($section[2] as $subIndex => $item): ?><li><?php if ($isPrivacy): ?><b><?= $index + 1 ?>.<?= $subIndex + 1 ?></b><?php endif; ?><?= e($item) ?></li><?php endforeach; ?></ul><?php endif; ?></div></section><?php endforeach; ?>
            <?php if (!$usesModernPolicyLayout): ?><section class="legal-contact" id="contato-legal"><span><i data-lucide="mail"></i></span><div><p class="legal-contact-kicker">Atendimento</p><h2>Fale com a MRDRIVES</h2><p>Nossa equipe está disponível nos canais oficiais.</p><div class="legal-contact-actions"><a href="mailto:<?= e($company['support_email']) ?>"><?= e($company['support_email']) ?></a><a href="https://wa.me/<?= e($whatsapp) ?>" target="_blank" rel="noopener">Falar pelo WhatsApp</a></div><?php if (!empty($company['legal_name']) || !empty($company['cnpj']) || !empty($company['address'])): ?><p class="legal-company-data"><?= e($company['legal_name'] ?: $company['trade_name']) ?><?php if ($company['cnpj']): ?> · CNPJ <?= e($company['cnpj']) ?><?php endif; ?></p><?php endif; ?></div></section><?php endif; ?>
        </div>
    </div>
</article>
